### ISSUE TITLE
len() of unsized object

### ISSUE THREAD

**Issue by valankar** [predict-idlab/plotly-resampler#110]
I get the following error trying to use this in my code:

```
Traceback (most recent call last):
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 351, in <module>
    main()
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 335, in main
    allocation_section = make_allocation_day_changes_section(daily_df, day_df)
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 278, in make_allocation_day_changes_section
    changes_section.add_trace(trace, row=1, col=1)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 915, in add_trace
    n_samples = len(dc.x)
```

Let me know what further details are needed.

**Comment by jonasvdd** [comment]
hi @valankar,

Amazing that you are using plotly-resampler! 🚀 

Which version of plotly-resampler do you use specifically?  To finde out, use this command:

```bash
pip freeze | grep -i plotly-resampler
```

Could you share what the `trace` property withholds of this line or share a minimal reproducible example of your issue?
>  changes_section.add_trace(trace, row=1, col=1)

**Comment by valankar** [comment]
Hi Jonas, here is the output. I tried pip first, then I installed with conda:

```
(investing) [pontus ~/code/accounts] pip freeze | grep -i plotly-resampler
plotly-resampler @ file:///home/conda/feedstock_root/build_artifacts/plotly-resampler_1659226996538/work
(investing) [pontus ~/code/accounts] conda list -f plotly-resampler
# packages in environment at /media/sdm1/valankar/software/anaconda3/envs/investing:
#
# Name                    Version                   Build  Channel
plotly-resampler          0.7.2.2            pyhd8ed1ab_1    conda-forge
```

You're right, I missed the last line, here is the full trace with a print of 'trace' just before the crash:

```
(investing) [pontus ~/code/accounts] ./plot2.py
Pie({
    'labels': [Investing, Liquid, Real Estate, Retirement],
    'uid': '7e8bdcfb-fee7-4ef1-8e77-3f31464c95c9',
    'values': [324643.4435821581, 112238.37140194925, 2710711.06,
               604360.2864262027]
})
Traceback (most recent call last):
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 352, in <module>
    main()
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 336, in main
    allocation_section = make_allocation_day_changes_section(daily_df, day_df)
  File "/media/sdm1/valankar/bin/accounts/plot2.py", line 279, in make_allocation_day_changes_section
    changes_section.add_trace(trace, row=1, col=1)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 915, in add_trace
    n_samples = len(dc.x)
TypeError: len() of unsized object
```

I will see if I can reproduce it with an isolated code.

**Comment by valankar** [comment]
Here is a quick reproduction:

```
#!/usr/bin/env python3

import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly_resampler import register_plotly_resampler


register_plotly_resampler(mode='auto')

labels = ['Investing', 'Liquid', 'Real Estate', 'Retirement']
values = [324643.4435821581, 112238.37140194925, 2710711.06, 604360.2864262027]
changes_section = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Asset Allocation', 'Changes in last 12 hours'),
    specs=[[{'type': 'pie'}, {'type': 'xy'}]]
    )
pie_total = go.Figure(data=[go.Pie(labels=labels, values=values)])
for trace in pie_total.data:
    print(trace)
    changes_section.add_trace(trace, row=1, col=1)
```

**Comment by jonasvdd** [comment]
Hi @valanka ,

good catch 🧐 there was indeed a bug with plotly-resampler. 

We apply this `len(...)` check too early; I fixed this issue; added a test and released `plotly-resampler=0.7.2.3`

Can you verify that everything works fine now?

Thanks again for pointing this issue out!

**Comment by valankar** [comment]
Thanks for the quick fix. I get an error installing with pip:

```
(investing) [pontus ~/code/accounts/web] pip install plotly-resampler==0.7.2.3
Collecting plotly-resampler==0.7.2.3
  Using cached plotly-resampler-0.7.2.3.tar.gz (41 kB)
  Installing build dependencies ... done
  ERROR: Error expected str, bytes or os.PathLike object, not list while executing command Getting requirements to build wheel
  Getting requirements to build wheel ... error
ERROR: Exception:
Traceback (most recent call last):
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper                                             status = run_func(*args)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper                                                          return func(self, options, args)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 341, in run                                                             requirement_set = resolver.resolve(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve                                            result = self._result = resolver.resolve(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve                                                       state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve                                                       self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria                                              if not criterion.candidates:
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__                                                        return bool(self._sequence)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__                                  return any(self)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>                                 return (c for c in iterator if id(c) not in self._incompatible_ids)                                                                                                                                    File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built                                candidate = func()
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link                          self._link_candidate_cache[link] = LinkCandidate(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__                                        super().__init__(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__                                        self.dist = self._prepare()
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare                                        dist = self._prepare_distribution()
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution                           return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)                                                                                                                           File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement                                    return self._prepare_linked_requirement(req, parallel_builds)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 497, in _prepare_linked_requirement                                   dist = _get_prepared_distribution(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution                                     abstract_dist.prepare_distribution_metadata(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs                                          build_reqs = self._get_build_requires_wheel()
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel                                     return backend.get_requires_for_build_wheel()
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel                                          return super().get_requires_for_build_wheel(config_settings=cs)
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel                                       return self._call_hook('get_requires_for_build_wheel', {
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 322, in _call_hook                                                         self._subprocess_runner(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner                                                          call_subprocess(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 141, in call_subprocess                                                 proc = subprocess.Popen(
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/subprocess.py", line 966, in __init__                                                                                          self._execute_child(args, executable, preexec_fn, close_fds,
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/subprocess.py", line 1762, in _execute_child                                                                                   env_list.append(k + b'=' + os.fsencode(v))
  File "/media/sdm1/valankar/software/anaconda3/envs/investing/lib/python3.10/os.py", line 810, in fsencode                                                                                                  filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not list
```

Not sure if there is something messed in my environment. However, I did try:

```
pip install plotly-resampler==0.7.2.2
```

and this worked. Perhaps something wrong with the latest version?

**Comment by valankar** [comment]
I applied the change manually to figure_resampler_interface.py and it seems to work. Maybe install error is unrelated.
