### ISSUE TITLE
Numpy error in lttb_py when a column has a constant boolean value

### ISSUE THREAD

**Issue by maxime-jolliet-airseas** [predict-idlab/plotly-resampler#182]
Hi,

This is a followup of https://github.com/predict-idlab/plotly-resampler/issues/171#issuecomment-1485302812.

The following code snippet raises an error.

It seems that lttb_py does not support having to deal with a column that is always "True" or "False".
The problem has been fixed in lttbc, but I work on WSL and lttbc seems to be incompatible.
plotly-resampler version is 0.8.3.2.

As @jonasvdd pointed out, working with an other aggregator, such as MinMaxAggregator, works well.

Thank you !

```
import numpy as np
import pandas as pd
from plotly_resampler import FigureResampler, EfficientLTTB
from plotly.subplots import make_subplots
import plotly.graph_objects as go

if __name__ == "__main__":
    n = 209650
    x_boolean = np.full(n, True)
    y = np.arange(n)
    df = pd.DataFrame(
        data={
            "x_boolean": x_boolean,
            "y": y
        },
        copy=False,
    )

    current_column = df["y"]
    time_series = df["x_boolean"][current_column.index].sort_values()

    figure = FigureResampler(
            make_subplots(
                rows=1,
                cols=1,
                shared_xaxes=True,
            ),
        )
    figure.add_trace(
        go.Scattergl(
            mode="lines",
            name="y",
            legendgroup=f"test",
            legendgrouptitle_text=f"test",
        ),
        hf_x=time_series,
        hf_y=current_column,
        downsampler=EfficientLTTB(interleave_gaps=False),
        max_n_samples=2000,
        row=1,
        col=1,
    )
``` 

```
/home/jolliet/git/graph/venv/bin/python /home/jolliet/git/graph/scripts/plotlyresampler.py
/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
  warnings.warn("Could not import lttbc; will use a (slower) python alternative.")
Traceback (most recent call last):
  File "/home/jolliet/git/graph/scripts/plotlyresampler.py", line 20, in <module>
    figure.add_trace(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 1011, in add_trace
    trace = self._check_update_trace_data(trace)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/figure_resampler/figure_resampler_interface.py", line 290, in _check_update_trace_data
    s_res: pd.Series = downsampler.aggregate(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregation_interface.py", line 157, in aggregate
    s = self._aggregate(s, n_out=n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py", line 295, in _aggregate
    return self.lttb._aggregate(s, n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py", line 90, in _aggregate
    index = LTTB_core.downsample(s_i, s_v, n_out)
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/algorithms/lttb_py.py", line 89, in downsample
    LTTB_core_py._argmax_area(
  File "/home/jolliet/git/graph/venv/lib/python3.9/site-packages/plotly_resampler/aggregation/algorithms/lttb_py.py", line 33, in _argmax_area
    + y_bucket * (avg_next_x - prev_x)
TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by jvdd** [comment]
Also linking #180 here (concerns issues w.r.t. compiling the lttb C code on Windows)
